### ISSUE TITLE
Cannot get list of activities (NumberFormatException)

### ISSUE THREAD

**Issue by vandeseer** [dustedrob/JStrava#52]
Hi and thanks for providing us with this library – I wanted to give it a shot. Unfortunately I cannot retrieve my activities, which I tried with the following code: 

    JStravaV3 strava = new JStravaV3(ACCESS_TOKEN);

    List<Activity> activities = strava.getCurrentAthleteActivitiesAll().stream()
            .filter(x -> x.getType().equals("StravaActivityType.run"))
            .collect(Collectors.toList());

I get this exception: 

    Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 40.1 at line 1 column 180 path $[0].total_elevation_gain
    	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:245)
    	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:235)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
    	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
    	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    	at com.google.gson.Gson.fromJson(Gson.java:887)
    	at com.google.gson.Gson.fromJson(Gson.java:852)
    	at com.google.gson.Gson.fromJson(Gson.java:801)
    	at com.google.gson.Gson.fromJson(Gson.java:773)
    	at org.jstrava.api.JStravaV3.getCurrentAthleteActivities(JStravaV3.java:309)
    	at org.jstrava.api.JStravaV3.getCurrentAthleteActivitiesAll(JStravaV3.java:287)
    	at org.vandeseer.stravanalyzor.MainJStrava.getDataFromStrava(MainJStrava.java:31)
    	at org.vandeseer.stravanalyzor.MainJStrava.main(MainJStrava.java:19)
    Caused by: java.lang.NumberFormatException: Expected an int but was 40.1 at line 1 column 180 path $[0].total_elevation_gain
    	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1196)
    	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:243)
    	... 13 more

**Comment by dustedrob** [comment]
Thanks and sorry for the delay. This probably fixes it.
